version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl
      - wordpress:/var/www/html
    networks:
      - cloud-1
    depends_on:
      - mysql
      - wordpress
      - phpmyadmin
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - cloud-1
    expose:
      - "3306"
    restart: unless-stopped
    env_file: .env

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    networks:
      - cloud-1
    expose:
      - "9000"
    depends_on:
      - mysql
    env_file: .env
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    networks:
      - cloud-1
    expose:
      - "80"
    depends_on:
      - mysql
    env_file: .env
    restart: unless-stopped
  
  node_exporter:
    image: prom/node-exporter:latest
    networks:
      - cloud-1
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - cloud-1
    depends_on:
      - node_exporter
  
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning/datasources/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/provisioning/dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/provisioning/dashboards/node-exporter.json:/etc/grafana/provisioning/dashboards/node-exporter.json
    networks:
      - cloud-1
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

volumes:
  mysql:
  wordpress:

networks:
  cloud-1:
    driver: bridge
