version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl
      - wordpress:/var/www/html
    networks:
      - cloud-1
    depends_on:
      - mysql
      - wordpress
      - phpmyadmin
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - cloud-1
    expose:
      - "3306"
    restart: unless-stopped
    env_file: .env

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    networks:
      - cloud-1
    expose:
      - "9000"
    depends_on:
      - mysql
    env_file: .env
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    networks:
      - cloud-1
    expose:
      - "80"
    depends_on:
      - mysql
    env_file: .env
    restart: unless-stopped

volumes:
  mysql:
  wordpress:

networks:
  cloud-1:
    driver: bridge
